version: '3'
services:
  sandbox-editor-notebook:
    restart: always
    image: sandbox-editor-notebook
    volumes:
      - ./:/usr/src/app
      - ../sandbox_app/:/usr/src/app/sandbox_app
      - ../fab_forms/:/usr/src/app/fab_forms
      - ../apithy/:/usr/src/app/apithy
      - ../apithy_react/:/usr/src/app/apithy_react
      - ../color_app/:/usr/src/app/color_app
      - ../carbon_calc/:/usr/src/app/carbon_calc
      - ../python_data_science_container:/usr/src/app/python_data_science_container
      - ../signals:/usr/src/app/signals
      - ../flask_js_template:/usr/src/app/flask_js_template
      - ../data_science_study:/usr/src/app/data_science_study
    env_file:
      - config/environment
      - config/secrets
    ports:
      - 8888:8989
    command: jupyter lab --port=8989 --ip=0.0.0.0 --allow-root --NotebookApp.password="sha1:f217aa434731:b01a46c5ffccfc413ccffc33c802882737ac2ccd"
