FROM python:3.6.4

RUN apt-get update && apt-get install -y libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 libav-tools

RUN mkdir -p /usr/src/app
ENV PYTHONPATH=$PYTHONPATH:/usr/src/app
ENV PYTHONPATH=/usr/src/app/src:$PYTHONPATH
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app
COPY src/requirements-app.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements-app.txt

# Copy static attrs (non dev) to /usr/src/app
COPY src/ src/
COPY bin/ bin/
COPY scripts/ scripts/
